a=input("Enter the Marks of 6 Students=\n1.")
a=int(a) 
b=input("2.")
b=int(b) 
c=input("3.")
c=int(c) 
d=input("4.")
d=int(d)  
e=input("5.")
e=int(e) 
f=input("6.")
f=int(f) 
Marks=[a,b,c,d,e,f]
Marks.sort() 
print(Marks) 